
[package]
edition = "2024"
name = "pico-fun"
version = "0.1.0"
license = "MIT or Apache-2.0"

[build-dependencies]
regex = "1.11.0"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
# embedded-hal = "1.0.0"
defmt = "1"
defmt-rtt = "1"
# pimoroni-pico-explorer = { version = "0.8.0", default-features = false }
# embedded-graphics = "0.7.1"
# st7789 = { version = "0.7", features = ["graphics"] }
# st7735-lcd = "0.8.1"
# ssd1306 = "0.7.1"
rp-binary-info = "0.1.1"
heapless = "0.9.2"

rp-pico = "0.9" # or rp2040-hal directly if you prefer
# embedded-hal = "0.2"
embedded-hal = "1.0.0"
embedded-graphics = "0.8"
# display-interface = "0.4"
# display-interface-spi = "0.4"
st7789 = { version = "0.7", default-features = false, features = ["graphics"] }
mipidsi = "0.9.0"
embedded-hal-bus = "0.3.0"

mousefood = { git = "https://github.com/j-g00da/mousefood", default-features = false }
ratatui = { version = "0.30.0-beta.1", default-features = false, features = [
    "portable-atomic",
] }
portable-atomic = { version = "1", default-features = false, features = [
    "critical-section",
] }
embedded-alloc = { git = "https://github.com/rust-embedded/embedded-alloc" }
# embedded-hal-compat = "0.13.0"

# embedded-graphics = { version = "0.8.1" }

# rp-pico = { version = "0.9.0", default-features = false }
# display-interface-spi = "0.4.1"

[patch.crates-io]
# embedded-graphics = { git = "https://github.com/embedded-graphics/embedded-graphics", tag = "embedded-graphics-v0.7.1" }
# embedded-graphics-core = { git = "https://github.com/embedded-graphics/embedded-graphics", tag = "embedded-graphics-core-v0.4.0" }

[target.'cfg( target_arch = "arm" )'.dependencies]
panic-probe = { version = "1", features = ["print-defmt"] }

[target.'cfg( target_arch = "riscv32" )'.dependencies]
panic-halt = { version = "1.0.0" }

[target.thumbv6m-none-eabi.dependencies]
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.11.0", features = ["rt", "critical-section-impl"] }

[target.riscv32imac-unknown-none-elf.dependencies]
rp235x-hal = { version = "0.3", features = ["rt", "critical-section-impl"] }

[target."thumbv8m.main-none-eabihf".dependencies]
rp235x-hal = { version = "0.3", features = ["rt", "critical-section-impl"] }
