
[package]
edition = "2024"
name = "pico-fun"
version = "0.1.0"
license = "MIT or Apache-2.0"

[build-dependencies]
regex = "1.11.0"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "1.0.0"
defmt = "1"
defmt-rtt = "1"
pimoroni-pico-explorer = { version = "0.8.0", default-features = false }
embedded-graphics = "0.7.1"
# st7789 = "0.6.1"
# st7735-lcd = "0.8.1"
# ssd1306 = "0.7.1"
rp-binary-info = "0.1.1"
heapless = "0.9.2"

# mousefood = "0.2.1"

# mousefood = { git = "https://github.com/j-g00da/mousefood" }
# ratatui = { version = "0.30.0-alpha.5", default-features = false }

mousefood = { git = "https://github.com/j-g00da/mousefood", default-features = false }
ratatui = { version = "0.30.0-beta.1", default-features = false }
kasuari = { version = "0.4.11", default-features = false, features = [
    "portable-atomic",
] }
portable-atomic = { version = "1.11", default-features = false, features = [
    "critical-section",
] }

[target.'cfg( target_arch = "arm" )'.dependencies]
panic-probe = { version = "1", features = ["print-defmt"] }

[target.'cfg( target_arch = "riscv32" )'.dependencies]
panic-halt = { version = "1.0.0" }

[target.thumbv6m-none-eabi.dependencies]
rp2040-boot2 = "0.3.0"
rp2040-hal = { version = "0.10.0", features = ["rt", "critical-section-impl"] }

[target.riscv32imac-unknown-none-elf.dependencies]
rp235x-hal = { version = "0.3", features = ["rt", "critical-section-impl"] }

[target."thumbv8m.main-none-eabihf".dependencies]
rp235x-hal = { version = "0.3", features = ["rt", "critical-section-impl"] }
